server:
  port: 9091
spring:
  application:
    name: stock-server
  cloud:
    nacos:
      server-addr: 192.168.234.122:8050
      discovery:
        username: nacos
        password: nacos
        namespace: public